# Generated by Django 3.0.5 on 2020-04-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20200429_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('NU', 'Normal'), ('SU', 'Admin')], default='NU', max_length=2),
        ),
    ]
